### ISSUE TITLE
Enum Idents

### ISSUE THREAD

**Issue by taylorSando** [SparkFund/spec-tacular#14]
What's the rationale for creating a new enum object behind the scenes each time a spec without any fields is created?  The way regular enum idents work is that you set the :db/ident to be the enum keyword.  I'm guessing that would throw off how you guys are setting spec-tacular/spec?

The problem for me right now is keeping datascript and datomic in some kind of sync.  Datascript is already weird with how it handles enum values.  I'm thinking I'm going to have to just use regular keywords for setting singleton style enums, such as statuses.  The only drawback, is I lose type checking for verifying the enum values.

**Comment by calvis** [comment]
Just to make sure we're on the same page -- this is the situation you're talking about:

```clojure
(defspec Stoplight
  [color :is-a :StoplightColor])

(defenum StoplightColor
  :Red :Yellow :Green)
```

where `Red`, `Yellow`, and `Green` are just specs with no fields.  You want to be able to statically typecheck the `color` field, which would work fine, but we make each `Red`, `Yellow, and `Green` as an actual object (and not just a keyword) and that doesn't work for your other purposes.

Right now we don't look at the nubmer of fields in any spec and I am hesitant to build a new semantics for existing syntax.  But I think you're suggesting something like this:

```clojure
(defenum Color ;; repurpose to define enums like Datomic's
  :red :yellow :green  <etc>)

(defunion StoplightColor ;; existing enums are more like unions
  :Color/red :Color/yellow :Color/green)
```

In Clojure, you would have `:Color/red` available to use as a keyword, the dynamic checks for `color?` and `stoplightcolor?`, all the static typechecking for `Color` as `(t/U ':Color/red <etc>)`, and `StoplightColor` as being the specified subset of colors.  The `color` field in `Spotlight` would still be a `SpotlightColor` type and would retain all that typechecking.

**Comment by taylorSando** [comment]
My concern was that behind the scenes in datomic each of the enum fields was creating a new object each time, rather than using the :db/ident semantics.  So you would create an actual database entry with a spec-tacular/spec value of the singleton object, along with a unique ID.  From what I read on the datomic forum, the ident-enum semantics were added for performance/storage reasons, rather than creating a new keyword each time, you could reference an existing enum entity.

If you were going to add to the enum semantics, you'd want to add something like a special ident-enum type that is created using :db/ident, rather than creating a whole new object.  It would be nice if you also had the enum semantics like https://github.com/Yuppiechef/datomic-schema

Though looking at the source code, that would seem to be a non-trivial addition.

**Comment by calvis** [comment]
I understand how it would be implemented, I just want to confirm that the syntax/semantics change I'm suggesting would address the issue you raised.  

We overload "enum" to mean "union" in our existing syntax, and allow specs within enums to have fields in them (which Datomic can't support directly with it's enumerations).  This is powerful, but not as efficient as it could be if we restricted it to just be things Datomic could directly support with enumerations.

So we could change `defenum` to be a special form just for Datomic enumerations, and redirect our existing enums to a new syntax `defunion` that is just a union of different specs.

**Comment by taylorSando** [comment]
That makes sense to me, it seems like what you have presently implemented for enums are really unions (specs with fields), and the proposed enums are more like what datomic already has, simply named entities that correspond to a single keyword.

```clojure
(defenum NamedType
  :A :B)

(defspec Something
  [type :is-a :NamedType])

;; Which would generate schema like this:
({:db/valueType :db.type/ref,  :db.install/_attribute :db.part/db,  
 :db/cardinality :db.cardinality/one,, :db/id #db/id[:db.part/db -1000240],
  :db/ident :something/type}
 [:db/add #db/id[:db.part/user -1000241] :db/ident :namedtype/a]
 [:db/add #db/id[:db.part/user -1000242] :db/ident :namedtype/b])

(create! {:conn *conn*} (something {:type :A}))
;; Would do something like this behind the scenes: 
[:db/add #db/id[:db.part/user -1000243] :something/type :namedtype/a]
```

**Comment by taylorSando** [comment]
Though you'd probably want to call the new stuff unions since I'm sure code already depends on how defenum is already defined.

**Comment by calvis** [comment]
Well, my general attitude is to keep stuff as "Datomic"y as possible -- and the way we define `defenum`s to be distinctly _unlike_ Datomic's enums does bother me.  Since we're pre-v1 I'm not too concerned with renaming our existing `defenum` to be `defunion` if it will be less confusing to users in the long run.

I think we're on the same page with the design.

**Comment by calvis** [comment]
Added in ae64cf6b3fca1ea96b7ef89e908638ff816a9aae.
