### ISSUE TITLE
The meaning of link

### ISSUE THREAD

**Issue by taylorSando** [SparkFund/spec-tacular#19]
What is the meaning of link when defining a spec?  The schema generated doesn't change, and the meaning isn't jumping out at me in the source code.

**Comment by calvis** [comment]
Links interact with `create-graph!` and `assoc!`.  They are always added to the database by-reference instead of by-value.  I'll try to put together some documentation that clarifies this behavior.

**Comment by calvis** [comment]
I added a wiki page that (I hope) explains what `:link` tries to accomplish.
