### ISSUE TITLE
Populate :db/doc

### ISSUE THREAD

**Issue by neverfox** [SparkFund/spec-tacular#25]
Is this supposed to get populated from the docstring used in `defspec`? If so, it doesn't seem to be working. If not, is there another way to get `:db/doc` populated from spec-tacular?

```clojure
(defspec Query
  "A search query"
  [text :is-a :string :identity :unique])

=> Query

#spark.spec_tacular.spec.Spec{:name :Query, :opts nil, :items
(#spark.spec_tacular.spec.Item{:name :text, :type [:one :string], :precondition nil,
:required? nil, :unique? true, :optional? nil, :identity? true, :default-value nil,
:parent-name nil}), :syntax (defspec Query "A search query" [text :is-a :string
:identity :unique]), :doc "A search query"}

=> (schema/from-spec Query)

({:db/id #db/id[:db.part/db -1000005], :db/ident :query/text,
:db/valueType :db.type/string, :db/cardinality :db.cardinality/one, :db/doc "",
:db.install/_attribute :db.part/db, :db/unique :db.unique/identity})
```

**Comment by calvis** [comment]
The parallel to `:db/doc` is the `:doc` keyword option to the `text` attribute itself, but amusingly enough that isn't hooked up during schema generation.  I can easily hook that up for you if that's what you want.

The `Query` spec itself is not represented on the database other than as a keyword value of `:spec-tacular/spec`, so I don't think there's a logical place for the `"A search query"` string to go atm.  Would be open to suggestions.

**Comment by neverfox** [comment]
Ah, okay, I wasn't aware of the `:doc` option, but if that needs to be hooked up, yes, I would appreciate it. You're right that it doesn't make sense to map then as I expected since `:db/doc` is attribute-level data, so that was a lapse in thinking on my part.
